"""SearchQueryEmbedding model for persisting query vectors from search sessions."""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from echoroo.models.base import Base

if TYPE_CHECKING:
    from echoroo.models.search_session import SearchSession


class SearchQueryEmbedding(Base):
    """Query embedding vector generated during a similarity search session.

    Stores each query vector used to perform vector similarity search so that
    the same vectors can be reused as positive training examples when building
    a custom classifier from search results.

    Attributes:
        id: Unique identifier (UUID, auto-generated by the database)
        search_session_id: FK to the search session that produced this vector
        species_key: Tag ID or scientific-name key used to group results
        source_label: Human-readable description of the reference audio source
        vector: 1536-dimensional embedding vector (Perch model output)
        created_at: Timestamp when the record was inserted
    """

    __tablename__ = "search_query_embeddings"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    search_session_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("search_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    species_key: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Tag ID or scientific name used as the grouping key for this query",
    )
    source_label: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Descriptive label for the reference audio source (e.g. url or upload path)",
    )

    # 1536-dimensional embedding vector (Perch v2.0)
    vector = mapped_column(Vector(1536), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    search_session: Mapped["SearchSession"] = relationship(
        "SearchSession",
        lazy="raise",
    )

    def __repr__(self) -> str:
        return (
            f"<SearchQueryEmbedding(id={self.id}, "
            f"search_session_id={self.search_session_id}, "
            f"species_key={self.species_key!r})>"
        )
