"""Transactional outbox writer + claim helpers (FR-076a, FR-076d, NFR-005).

The outbox pattern decouples a business transaction (e.g. removing a project
member) from the side-effects that must happen *exactly once* but must not
block the API response (e.g. revoking the user's API keys, emitting an
audit log row that survives a worker crash). The flow is:

1. The HTTP handler INSERTs a row into ``outbox_events`` inside the **same
   database transaction** as the business mutation. Because the INSERT and
   the mutation share the transaction, the outbox row exists if and only
   if the business change was committed (FR-076a).

2. A pool of Celery worker-cpu processes polls the table with
   ``SELECT ... FOR UPDATE SKIP LOCKED`` so that 4 parallel workers never
   double-process the same row (research.md §6).

3. Each worker invokes the registered handler for ``event_type``. The
   handler MUST be idempotent — if the worker crashes between handler
   completion and ``mark_done``, the row is re-claimed and the handler
   runs again. Idempotency is achieved by keying side-effects on
   ``idempotency_key`` (FR-076a, SC-021).

4. After ``MAX_RETRY`` consecutive failures the row transitions to
   ``status='dead_letter'`` and a superuser PagerDuty alert fires. Until
   resolution, ``OutboxStallDetector`` reports stalled workers so that
   middleware can flip the global ``enforce_at_auth_time`` flag and fall
   back to synchronous permission checks (research.md §6, FR-076d).

The module exposes a small functional surface (no ORM model class is
imported here — the baseline migration is the source of truth for the
table schema) so that it can run inside a Celery worker that has not yet
loaded the full SQLAlchemy registry.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from typing import Any, Final
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)


# -- Retry policy (data-model.md §3.18) ---------------------------------------

#: Maximum number of times a single outbox row may be retried before the
#: worker promotes it to ``dead_letter``. Aligned with research.md §6.
MAX_RETRY: Final[int] = 5

#: Worker-side Celery retry budget — *separate* from the outbox row retry
#: counter. The processor task itself uses ``self.retry`` up to 3 times
#: with exponential backoff for transient failures (e.g. broker hiccups)
#: before letting the row's ``retry_count`` advance.
CELERY_TASK_MAX_RETRIES: Final[int] = 3

#: Per-row backoff schedule (seconds) indexed by ``retry_count``. After
#: the 5th failure the row enters ``dead_letter`` so this list is only
#: consulted for indices 0..MAX_RETRY-1.
BACKOFF_SCHEDULE: Final[tuple[int, ...]] = (1, 4, 16, 64, 256)

#: Hard cap on any computed backoff (seconds). Acts as a safety net if
#: somebody bumps :data:`MAX_RETRY` and the schedule is regenerated by
#: the ``2**attempt`` rule below.
BACKOFF_CAP_SECONDS: Final[int] = 600

#: Default batch size for :func:`claim_batch` (matches research.md §6 SLO
#: of p95 ≤ 10s with 4 worker pods polling at 1Hz).
DEFAULT_CLAIM_BATCH_SIZE: Final[int] = 50

#: How long a row may sit in ``status='pending'`` before the system
#: considers the outbox stalled and asks middleware to enforce at
#: authentication time (FR-076d, SC-021).
STALL_THRESHOLD: Final[timedelta] = timedelta(minutes=5)


# -- Status constants ---------------------------------------------------------

STATUS_PENDING: Final[str] = "pending"
STATUS_PROCESSING: Final[str] = "processing"
STATUS_DONE: Final[str] = "done"
STATUS_FAILED: Final[str] = "failed"
STATUS_DEAD_LETTER: Final[str] = "dead_letter"


# -- Helpers ------------------------------------------------------------------


def _compute_backoff_seconds(attempt: int) -> int:
    """Return the next-retry delay in seconds for a given attempt number.

    The schedule prefers :data:`BACKOFF_SCHEDULE` for the first
    :data:`MAX_RETRY` attempts; beyond that it falls back to a generic
    ``2**attempt`` formula capped at :data:`BACKOFF_CAP_SECONDS`. The
    fallback is unreachable under normal operation because
    :func:`mark_failed` promotes the row to ``dead_letter`` once
    ``retry_count >= MAX_RETRY``, but it keeps the helper robust if
    callers want to compute a hypothetical next retry for monitoring.
    """
    if attempt < 0:
        attempt = 0
    if attempt < len(BACKOFF_SCHEDULE):
        return BACKOFF_SCHEDULE[attempt]
    # Fallback / safety net.
    raw: int = 2**attempt
    return int(min(raw, BACKOFF_CAP_SECONDS))


# -- Public API ---------------------------------------------------------------


async def enqueue(
    session: AsyncSession,
    *,
    event_type: str,
    payload: dict[str, Any],
    idempotency_key: str,
    available_at: datetime | None = None,
) -> UUID:
    """Insert an event into the outbox table.

    The INSERT participates in the caller's transaction (the function
    deliberately does **not** commit) so the row is persisted iff the
    business mutation commits. A ``UNIQUE`` violation on
    ``idempotency_key`` is treated as success: the existing row's id is
    returned without raising. This keeps the handler call-site idempotent
    even if a retry storms two enqueue attempts.

    Args:
        session: Caller's async session (joined transaction).
        event_type: Event discriminator, e.g. ``"api_key_revoke_on_member_removal"``.
        payload: Free-form JSONB payload. **Must not** contain raw lat/lng
            keys — enforce via :class:`echoroo.workers._celery_payload.CeleryTaskPayload`
            on the producing side (FR-028b).
        idempotency_key: Globally unique key (UNIQUE INDEX). Used by the
            worker to dedupe audit log writes (FR-076a, SC-021).
        available_at: Earliest moment the worker may pick the row up.
            Defaults to ``now`` (immediately eligible).

    Returns:
        The ``id`` of the inserted (or pre-existing) outbox row.
    """
    if not event_type:
        raise ValueError("event_type must be a non-empty string")
    if not idempotency_key:
        raise ValueError("idempotency_key must be a non-empty string")

    now = datetime.now(UTC)
    next_retry_at = available_at if available_at is not None else now

    # Use ON CONFLICT (idempotency_key) DO UPDATE SET ... so we can RETURN
    # both newly-inserted and already-existing rows uniformly. The fake
    # update of ``retry_count = retry_count`` is a no-op SET that lets the
    # RETURNING clause fire on the conflict path (Postgres requires SET
    # for DO UPDATE).
    stmt = sa.text(
        """
        INSERT INTO outbox_events
            (event_type, payload, status, retry_count, next_retry_at, idempotency_key, created_at)
        VALUES
            (:event_type, CAST(:payload AS JSONB), :status, 0, :next_retry_at, :idempotency_key, :created_at)
        ON CONFLICT (idempotency_key) DO UPDATE
            SET retry_count = outbox_events.retry_count
        RETURNING id
        """
    )
    import json

    result = await session.execute(
        stmt,
        {
            "event_type": event_type,
            "payload": json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str),
            "status": STATUS_PENDING,
            "next_retry_at": next_retry_at,
            "idempotency_key": idempotency_key,
            "created_at": now,
        },
    )
    row = result.first()
    if row is None:  # pragma: no cover — RETURNING always yields a row.
        raise RuntimeError("outbox enqueue returned no row")
    inserted_id: UUID = row[0]
    return inserted_id


async def claim_batch(
    session: AsyncSession,
    *,
    batch_size: int = DEFAULT_CLAIM_BATCH_SIZE,
    worker_id: str,
) -> list[dict[str, Any]]:
    """Atomically claim up to ``batch_size`` due rows for a worker.

    Implements the canonical ``SELECT ... FOR UPDATE SKIP LOCKED`` pattern
    so that 4 parallel workers can poll concurrently without any pair
    locking the same row (research.md §6 / FR-076d).

    Two-step protocol per claim:

    1. Inside an open transaction (the caller is responsible for the
       BEGIN / COMMIT — the function does **not** commit), run the
       locking ``SELECT`` to materialise the rows.
    2. ``UPDATE`` the same rows to ``status='processing'`` so that the
       worker monitor sees them as in-flight even after the transaction
       commits.

    Args:
        session: Caller's async session (must be in a transaction).
        batch_size: Maximum rows to claim. Defaults to 50.
        worker_id: Opaque identifier (host:pid) recorded in the row's
            ``last_error`` column for debugging — not for correctness.

    Returns:
        List of row dicts (id / event_type / payload / retry_count /
        idempotency_key). Empty list when the queue is drained.
    """
    if batch_size <= 0:
        raise ValueError("batch_size must be positive")

    select_stmt = sa.text(
        """
        SELECT id, event_type, payload, retry_count, idempotency_key
        FROM outbox_events
        WHERE status = :pending
          AND (next_retry_at IS NULL OR next_retry_at <= :now)
        ORDER BY created_at ASC
        LIMIT :batch_size
        FOR UPDATE SKIP LOCKED
        """
    )

    now = datetime.now(UTC)
    select_result = await session.execute(
        select_stmt,
        {"pending": STATUS_PENDING, "now": now, "batch_size": batch_size},
    )
    rows: list[dict[str, Any]] = [dict(row) for row in select_result.mappings().all()]
    if not rows:
        return []

    ids = [r["id"] for r in rows]

    # Mark as processing in the same transaction. The UPDATE intentionally
    # does NOT bump retry_count — the row is still in-flight, not failed.
    update_stmt = sa.text(
        """
        UPDATE outbox_events
           SET status = :processing,
               last_error = :worker_id
         WHERE id = ANY(:ids)
        """
    )
    await session.execute(
        update_stmt,
        {"processing": STATUS_PROCESSING, "worker_id": worker_id, "ids": ids},
    )
    return rows


async def mark_done(session: AsyncSession, event_id: UUID) -> None:
    """Mark an outbox row as successfully processed.

    The handler is responsible for being idempotent — if the worker
    crashes between handler completion and this UPDATE, the row stays in
    ``processing`` and a watchdog (T093, future phase) will eventually
    reset it to ``pending`` so a retry can run. Re-running the handler
    against the same ``idempotency_key`` MUST be a no-op (FR-076a).
    """
    stmt = sa.text(
        """
        UPDATE outbox_events
           SET status = :done,
               processed_at = :now,
               last_error = NULL
         WHERE id = :id
        """
    )
    await session.execute(
        stmt,
        {"done": STATUS_DONE, "now": datetime.now(UTC), "id": event_id},
    )


async def mark_failed(
    session: AsyncSession,
    event_id: UUID,
    *,
    error: str,
    current_retry_count: int,
) -> str:
    """Mark a row as failed and schedule the next retry — or dead-letter it.

    Returns the resulting status (``"failed"`` if a retry is queued,
    ``"dead_letter"`` if the budget is exhausted) so the caller can log
    accordingly.
    """
    next_attempt = current_retry_count + 1
    if next_attempt >= MAX_RETRY:
        stmt = sa.text(
            """
            UPDATE outbox_events
               SET status = :dead_letter,
                   retry_count = :retry_count,
                   last_error = :error,
                   next_retry_at = NULL
             WHERE id = :id
            """
        )
        await session.execute(
            stmt,
            {
                "dead_letter": STATUS_DEAD_LETTER,
                "retry_count": next_attempt,
                "error": error[:8000],  # Bounded to keep TEXT row reasonable.
                "id": event_id,
            },
        )
        logger.error(
            "outbox event %s moved to dead_letter after %d attempts: %s",
            event_id,
            next_attempt,
            error,
        )
        return STATUS_DEAD_LETTER

    backoff = _compute_backoff_seconds(next_attempt)
    next_retry_at = datetime.now(UTC) + timedelta(seconds=backoff)
    stmt = sa.text(
        """
        UPDATE outbox_events
           SET status = :pending,
               retry_count = :retry_count,
               last_error = :error,
               next_retry_at = :next_retry_at
         WHERE id = :id
        """
    )
    await session.execute(
        stmt,
        {
            "pending": STATUS_PENDING,
            "retry_count": next_attempt,
            "error": error[:8000],
            "next_retry_at": next_retry_at,
            "id": event_id,
        },
    )
    return STATUS_FAILED


async def count_pending_older_than(
    session: AsyncSession,
    age: timedelta,
) -> int:
    """Return the number of pending rows whose ``created_at`` is older than ``age``.

    Used by :class:`OutboxStallDetector` and external dashboards to spot
    stuck workers (FR-076d). ``status='processing'`` rows are *not*
    counted because they are by construction in-flight; a stuck worker
    will eventually be reaped by the watchdog and the row will return to
    ``pending``.
    """
    threshold = datetime.now(UTC) - age
    stmt = sa.text(
        """
        SELECT COUNT(*) AS cnt
          FROM outbox_events
         WHERE status = :pending
           AND created_at < :threshold
        """
    )
    result = await session.execute(stmt, {"pending": STATUS_PENDING, "threshold": threshold})
    row = result.first()
    if row is None:  # pragma: no cover — COUNT always returns one row.
        return 0
    count: int = int(row[0])
    return count


# -- Stall detector / fallback ------------------------------------------------


class OutboxStallDetector:
    """Detects whether the outbox queue is stalled and triggers fallback.

    When the workers stop draining the queue (e.g. a deployment outage),
    permission revocations queued via the outbox would otherwise be
    silently delayed. The fallback path (`enforce_at_auth_time=true`)
    forces the auth middleware to recompute permissions on every request
    rather than trusting cached values, restoring correctness at the
    cost of latency until the queue catches up (FR-076d, SC-021).
    """

    def __init__(self, threshold: timedelta = STALL_THRESHOLD) -> None:
        """Initialise with the stall threshold (defaults to 5 minutes)."""
        self._threshold = threshold

    @property
    def threshold(self) -> timedelta:
        """Return the configured stall threshold."""
        return self._threshold

    async def is_stalled(self, session: AsyncSession) -> bool:
        """Return ``True`` if any pending rows exceed the threshold age."""
        count = await count_pending_older_than(session, self._threshold)
        return count > 0

    async def should_enforce_at_auth_time(self, session: AsyncSession) -> bool:
        """Alias kept for clarity at call-sites in the auth middleware.

        Returns ``True`` when the auth middleware should bypass permission
        caches and recompute on every request (the fallback mode).
        """
        return await self.is_stalled(session)


__all__ = [
    "BACKOFF_CAP_SECONDS",
    "BACKOFF_SCHEDULE",
    "CELERY_TASK_MAX_RETRIES",
    "DEFAULT_CLAIM_BATCH_SIZE",
    "MAX_RETRY",
    "OutboxStallDetector",
    "STALL_THRESHOLD",
    "STATUS_DEAD_LETTER",
    "STATUS_DONE",
    "STATUS_FAILED",
    "STATUS_PENDING",
    "STATUS_PROCESSING",
    "claim_batch",
    "count_pending_older_than",
    "enqueue",
    "mark_done",
    "mark_failed",
]
