openapi: 3.1.0
info:
  title: Echoroo API Tokens API
  version: 1.0.0
  description: API token management endpoints

paths:
  /api/v1/api-tokens:
    get:
      operationId: listApiTokens
      summary: List API tokens
      description: Get list of user's API tokens
      tags: [API Tokens]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      operationId: createApiToken
      summary: Create API token
      description: Create new API token
      tags: [API Tokens]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTokenRequest'
      responses:
        '201':
          description: Token created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenCreateResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/api-tokens/{token_id}:
    get:
      operationId: getApiToken
      summary: Get API token
      description: Get token details by ID
      tags: [API Tokens]
      security:
        - cookieAuth: []
      parameters:
        - name: token_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Token details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: deleteApiToken
      summary: Delete API token
      description: Revoke and delete API token
      tags: [API Tokens]
      security:
        - cookieAuth: []
      parameters:
        - name: token_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Token deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  responses:
    Unauthorized:
      description: Not authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    TokenListResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TokenResponse'

    TokenResponse:
      type: object
      required: [id, name, is_active, created_at]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        last_used_at:
          type: string
          format: date-time
          nullable: true
        expires_at:
          type: string
          format: date-time
          nullable: true
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time

    TokenCreateResponse:
      type: object
      required: [id, name, token, is_active, created_at]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        token:
          type: string
          description: Full token (only shown once at creation)
        expires_at:
          type: string
          format: date-time
          nullable: true
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time

    CreateTokenRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          maxLength: 100
        expires_in_days:
          type: integer
          minimum: 1
          maximum: 365
          description: Optional expiration in days

    ErrorResponse:
      type: object
      required: [detail]
      properties:
        detail:
          type: string
