openapi: 3.1.0
info:
  title: Echoroo Projects API
  version: 1.0.0
  description: Project management endpoints

paths:
  /api/v1/projects:
    get:
      operationId: listProjects
      summary: List projects
      description: Get paginated list of user's projects
      tags: [Projects]
      security:
        - cookieAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: search
          in: query
          schema:
            type: string
          description: Search by project name
        - name: role
          in: query
          schema:
            type: string
            enum: [admin, member, viewer]
          description: Filter by user's role
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      operationId: createProject
      summary: Create project
      description: Create a new project
      tags: [Projects]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectCreateRequest'
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetailResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/projects/{project_id}:
    get:
      operationId: getProject
      summary: Get project details
      description: Get project by ID
      tags: [Projects]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetailResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      operationId: updateProject
      summary: Update project
      description: Update project settings (admin only)
      tags: [Projects]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectUpdateRequest'
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetailResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: deleteProject
      summary: Delete project
      description: Delete project (owner only)
      tags: [Projects]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Project deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/projects/{project_id}/members:
    get:
      operationId: listProjectMembers
      summary: List project members
      description: Get list of project members
      tags: [Project Members]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of members
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      operationId: addProjectMember
      summary: Add project member
      description: Add existing user to project (admin only)
      tags: [Project Members]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMemberRequest'
      responses:
        '201':
          description: Member added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '400':
          description: User already member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/projects/{project_id}/members/{user_id}:
    patch:
      operationId: updateProjectMember
      summary: Update member role
      description: Change member's role (admin only)
      tags: [Project Members]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMemberRequest'
      responses:
        '200':
          description: Member updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: removeProjectMember
      summary: Remove member
      description: Remove member from project (admin only)
      tags: [Project Members]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Member removed
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/projects/{project_id}/invitations:
    get:
      operationId: listInvitations
      summary: List pending invitations
      description: Get pending invitations (admin only)
      tags: [Project Invitations]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of invitations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      operationId: createInvitation
      summary: Create invitation
      description: Send invitation email (admin only)
      tags: [Project Invitations]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvitationRequest'
      responses:
        '201':
          description: Invitation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationResponse'
        '400':
          description: User already member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/projects/{project_id}/invitations/{invitation_id}:
    delete:
      operationId: cancelInvitation
      summary: Cancel invitation
      description: Cancel pending invitation (admin only)
      tags: [Project Invitations]
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: invitation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Invitation cancelled
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/invitations/accept:
    post:
      operationId: acceptInvitation
      summary: Accept invitation
      description: Accept project invitation with token
      tags: [Project Invitations]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptInvitationRequest'
      responses:
        '200':
          description: Invitation accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetailResponse'
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  responses:
    Unauthorized:
      description: Not authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ProjectListResponse:
      type: object
      required: [items, total, page, per_page, pages]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProjectSummary'
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
        pages:
          type: integer

    ProjectSummary:
      type: object
      required: [id, name, visibility, owner, my_role, created_at]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
          nullable: true
        visibility:
          type: string
          enum: [private, public]
        owner:
          $ref: '#/components/schemas/UserBrief'
        my_role:
          type: string
          enum: [admin, member, viewer]
        member_count:
          type: integer
        created_at:
          type: string
          format: date-time

    ProjectDetailResponse:
      type: object
      required: [id, name, visibility, owner, my_role, created_at]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
          nullable: true
        target_taxa:
          type: string
          nullable: true
        visibility:
          type: string
          enum: [private, public]
        owner:
          $ref: '#/components/schemas/UserBrief'
        my_role:
          type: string
          enum: [admin, member, viewer]
        member_count:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ProjectCreateRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          maxLength: 200
        description:
          type: string
        target_taxa:
          type: string
          maxLength: 500
        visibility:
          type: string
          enum: [private, public]
          default: private

    ProjectUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 200
        description:
          type: string
        target_taxa:
          type: string
          maxLength: 500
        visibility:
          type: string
          enum: [private, public]

    MemberListResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MemberResponse'

    MemberResponse:
      type: object
      required: [id, user, role, joined_at]
      properties:
        id:
          type: string
          format: uuid
        user:
          $ref: '#/components/schemas/UserBrief'
        role:
          type: string
          enum: [admin, member, viewer]
        joined_at:
          type: string
          format: date-time
        invited_by:
          $ref: '#/components/schemas/UserBrief'
          nullable: true

    AddMemberRequest:
      type: object
      required: [user_id, role]
      properties:
        user_id:
          type: string
          format: uuid
        role:
          type: string
          enum: [admin, member, viewer]

    UpdateMemberRequest:
      type: object
      required: [role]
      properties:
        role:
          type: string
          enum: [admin, member, viewer]

    InvitationListResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/InvitationResponse'

    InvitationResponse:
      type: object
      required: [id, email, role, invited_by, expires_at, created_at]
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
          enum: [admin, member, viewer]
        invited_by:
          $ref: '#/components/schemas/UserBrief'
        expires_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

    CreateInvitationRequest:
      type: object
      required: [email, role]
      properties:
        email:
          type: string
          format: email
        role:
          type: string
          enum: [admin, member, viewer]

    AcceptInvitationRequest:
      type: object
      required: [token]
      properties:
        token:
          type: string

    UserBrief:
      type: object
      required: [id, email]
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        display_name:
          type: string
          nullable: true

    ErrorResponse:
      type: object
      required: [detail]
      properties:
        detail:
          type: string
