"""add_bit_depth_to_recording

Revision ID: 09290a9be9ed
Revises: 7ea39f3ee58d
Create Date: 2025-12-01 22:44:47.084934

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09290a9be9ed"
down_revision: Union[str, None] = "7ea39f3ee58d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_membership")
    op.drop_table("group")
    op.add_column(
        "recording", sa.Column("bit_depth", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recording", "bit_depth")
    op.create_table(
        "group",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("created_by_id", sa.CHAR(length=36), nullable=True),
        sa.Column("created_on", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
            name="fk_group_created_by_id_user",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_group"),
        sa.UniqueConstraint("name", name="uq_group_name"),
    )
    op.create_table(
        "group_membership",
        sa.Column("group_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.CHAR(length=36), nullable=False),
        sa.Column(
            "role",
            sa.VARCHAR(length=7),
            server_default=sa.text("'member'"),
            nullable=False,
        ),
        sa.Column("created_on", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name="fk_group_membership_group_id_group",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="fk_group_membership_user_id_user",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "group_id", "user_id", name="pk_group_membership"
        ),
    )
    # ### end Alembic commands ###
