"""Pydantic schemas for request/response validation."""

from echoroo.schemas.clip import (
    ClipCreate,
    ClipDetailResponse,
    ClipGenerateRequest,
    ClipGenerateResponse,
    ClipListResponse,
    ClipResponse,
    ClipUpdate,
    RecordingSummary,
)
from echoroo.schemas.dataset import (
    DatasetCreate,
    DatasetDetailResponse,
    DatasetListResponse,
    DatasetResponse,
    DatasetStatisticsResponse,
    DatasetUpdate,
    DirectoryInfo,
    DirectoryListResponse,
    ExportRequest,
    ImportRequest,
    ImportStatusResponse,
    LicenseSummary,
    RecorderSummary,
    SiteSummary,
    UserSummary,
)
from echoroo.schemas.recording import (
    DatasetSummary,
    PlaybackParams,
    RecordingDetailResponse,
    RecordingListResponse,
    RecordingResponse,
    RecordingUpdate,
    SiteSummaryForRecording,
    SpectrogramParams,
)
from echoroo.schemas.site import (
    H3FromCoordinatesRequest,
    H3FromCoordinatesResponse,
    H3ValidationRequest,
    H3ValidationResponse,
    SiteCreate,
    SiteDetailResponse,
    SiteListResponse,
    SiteResponse,
    SiteUpdate,
)

__all__ = [
    # Clip schemas
    "ClipCreate",
    "ClipDetailResponse",
    "ClipGenerateRequest",
    "ClipGenerateResponse",
    "ClipListResponse",
    "ClipResponse",
    "ClipUpdate",
    "RecordingSummary",
    # Dataset schemas
    "DatasetCreate",
    "DatasetDetailResponse",
    "DatasetListResponse",
    "DatasetResponse",
    "DatasetStatisticsResponse",
    "DatasetUpdate",
    "DirectoryInfo",
    "DirectoryListResponse",
    "ExportRequest",
    "ImportRequest",
    "ImportStatusResponse",
    "LicenseSummary",
    "RecorderSummary",
    "SiteSummary",
    "UserSummary",
    # Recording schemas
    "DatasetSummary",
    "PlaybackParams",
    "RecordingDetailResponse",
    "RecordingListResponse",
    "RecordingResponse",
    "RecordingUpdate",
    "SiteSummaryForRecording",
    "SpectrogramParams",
    # Site schemas
    "H3FromCoordinatesRequest",
    "H3FromCoordinatesResponse",
    "H3ValidationRequest",
    "H3ValidationResponse",
    "SiteCreate",
    "SiteDetailResponse",
    "SiteListResponse",
    "SiteResponse",
    "SiteUpdate",
]
