"""Pydantic schemas for request/response validation."""

from echoroo.schemas.clip import (
    ClipCreate,
    ClipDetailResponse,
    ClipGenerateRequest,
    ClipGenerateResponse,
    ClipListResponse,
    ClipResponse,
    ClipUpdate,
    RecordingSummary,
)
from echoroo.schemas.dataset import (
    DatasetCreate,
    DatasetDetailResponse,
    DatasetListResponse,
    DatasetResponse,
    DatasetStatisticsResponse,
    DatasetUpdate,
    ExportRequest,
    ImportRequest,
    ImportStatusResponse,
    LicenseSummary,
    RecorderSummary,
    SiteSummary,
    UserSummary,
)
from echoroo.schemas.recording import (
    DatasetSummary as RecordingDatasetSummary,
)
from echoroo.schemas.recording import (
    PlaybackParams,
    RecordingDetailResponse,
    RecordingListResponse,
    RecordingResponse,
    RecordingUpdate,
    SiteSummaryForRecording,
    SpectrogramParams,
)
from echoroo.schemas.site import (
    H3FromCoordinatesRequest,
    H3FromCoordinatesResponse,
    H3ValidationRequest,
    H3ValidationResponse,
    SiteCreate,
    SiteDetailResponse,
    SiteListResponse,
    SiteResponse,
    SiteUpdate,
)
from echoroo.schemas.tag import (
    GBIFSuggestion,
    TagCreate,
    TagDetailResponse,
    TagListResponse,
    TagResponse,
    TagStatistic,
    TagUpdate,
)
from echoroo.schemas.upload import (
    CompleteUploadRequest,
    CompleteUploadResponse,
    CreateUploadSessionRequest,
    CreateUploadSessionResponse,
    UploadFilePresignedResponse,
    UploadFileRequest,
    UploadFileStatusResponse,
    UploadSessionStatusResponse,
)

__all__ = [
    # Clip schemas
    "ClipCreate",
    "ClipDetailResponse",
    "ClipGenerateRequest",
    "ClipGenerateResponse",
    "ClipListResponse",
    "ClipResponse",
    "ClipUpdate",
    "RecordingSummary",
    # Dataset schemas
    "DatasetCreate",
    "DatasetDetailResponse",
    "DatasetListResponse",
    "DatasetResponse",
    "DatasetStatisticsResponse",
    "DatasetUpdate",
    "ExportRequest",
    "ImportRequest",
    "ImportStatusResponse",
    "LicenseSummary",
    "RecorderSummary",
    "SiteSummary",
    "UserSummary",
    # Recording schemas
    "RecordingDatasetSummary",
    "PlaybackParams",
    "RecordingDetailResponse",
    "RecordingListResponse",
    "RecordingResponse",
    "RecordingUpdate",
    "SiteSummaryForRecording",
    "SpectrogramParams",
    # Site schemas
    "H3FromCoordinatesRequest",
    "H3FromCoordinatesResponse",
    "H3ValidationRequest",
    "H3ValidationResponse",
    "SiteCreate",
    "SiteDetailResponse",
    "SiteListResponse",
    "SiteResponse",
    "SiteUpdate",
    # Tag schemas
    "GBIFSuggestion",
    "TagCreate",
    "TagDetailResponse",
    "TagListResponse",
    "TagResponse",
    "TagStatistic",
    "TagUpdate",
    # Upload schemas
    "CompleteUploadRequest",
    "CompleteUploadResponse",
    "CreateUploadSessionRequest",
    "CreateUploadSessionResponse",
    "UploadFilePresignedResponse",
    "UploadFileRequest",
    "UploadFileStatusResponse",
    "UploadSessionStatusResponse",
]
