"""Re-key sensitive-species masking onto ``taxa.id`` (taxonomy WS-A v2 slice 4).

Revision ID: 0034
Revises: 0033
Create Date: 2026-08-23

``taxon_sensitivities.taxon_id`` and
``project_taxon_sensitivity_overrides.taxon_id`` were ``VARCHAR(64)`` columns
nominally holding a "GBIF species key". In practice the key-space was split
three ways and the masking pipeline could never match reliably:

* the IUCN sync worker wrote the **IUCN SIS taxonid**,
* the MoE Red Data Book seeder wrote a **GBIF species key**,
* the detections reader compared against ``str(tag.gbif_taxon_key)``,

and ~6,520 of 6,523 local ``taxa`` rows have ``gbif_taxon_key IS NULL`` anyway.
Net effect: IUCN-sourced sensitivity rows never masked anything.

This migration re-keys both tables onto the platform's immutable species
identity — ``taxa.id`` (UUID) — so every writer and the reader share one
key-space. Both writers now resolve incoming rows to a local taxon by
scientific name before upserting.

Data handling: Echoroo is pre-launch and both tables are operator-seeded
reference data that is regenerated by re-running the IUCN sync / MoE seeder.
The existing rows carry keys from three incompatible namespaces and therefore
cannot be back-mapped deterministically, so this migration TRUNCATEs both
tables rather than shipping a lossy back-fill. This is sanctioned by the
product owner for the pre-launch window.

FK semantics: **both** tables use ``ON DELETE RESTRICT``.

* ``taxon_sensitivities`` — this is a masking *guard* table. An earlier draft
  used CASCADE on the theory that a sensitivity row is disposable derived
  data, but that makes a ``taxa`` delete (or a re-seed that deletes and
  re-inserts rows) silently empty the guard table and unmask every protected
  species. Failing the delete loudly is the only safe direction; an operator
  who really wants to drop a taxon must retire its sensitivity rows first.
* ``project_taxon_sensitivity_overrides`` — override rows are additionally
  referenced by the FR-111 superuser approval / audit trail, so a taxon
  delete must not silently erase an audited decision either.

The three CHECK constraints (``ck_taxon_sensitivities_h3_discrete``,
``ck_taxon_overrides_h3_discrete``, ``ck_taxon_overrides_direction_vs_approval``)
are untouched — none of them reference ``taxon_id``.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0034"
down_revision: str | None = "0033"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


SENSITIVITIES_TABLE = "taxon_sensitivities"
OVERRIDES_TABLE = "project_taxon_sensitivity_overrides"

SENSITIVITY_FK = "fk_taxon_sensitivities_taxon_id_taxa"
OVERRIDE_FK = "fk_taxon_overrides_taxon_id_taxa"


def upgrade() -> None:
    # --- 1. Drop everything that depends on the old string column ------------
    op.drop_index("ix_taxon_sensitivities_taxon", table_name=SENSITIVITIES_TABLE)
    op.drop_constraint(
        "ux_taxon_sensitivities_taxon_source",
        SENSITIVITIES_TABLE,
        type_="unique",
    )
    op.drop_index("ux_taxon_overrides_applied_unique", table_name=OVERRIDES_TABLE)
    op.drop_index("ix_taxon_overrides_taxon_approval", table_name=OVERRIDES_TABLE)

    # --- 2. Discard the un-mappable reference rows (pre-launch, sanctioned) --
    # See the module docstring: the three writers used three different
    # key-spaces, so there is no deterministic back-fill. Re-run the IUCN sync
    # and the MoE seeder after deploying.
    op.execute(sa.text(f"TRUNCATE TABLE {OVERRIDES_TABLE}"))
    op.execute(sa.text(f"TRUNCATE TABLE {SENSITIVITIES_TABLE}"))

    # --- 3. Swap the column type (drop + add; tables are empty) --------------
    op.drop_column(SENSITIVITIES_TABLE, "taxon_id")
    op.add_column(
        SENSITIVITIES_TABLE,
        sa.Column("taxon_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.drop_column(OVERRIDES_TABLE, "taxon_id")
    op.add_column(
        OVERRIDES_TABLE,
        sa.Column("taxon_id", postgresql.UUID(as_uuid=True), nullable=False),
    )

    # --- 4. Wire the FKs to the canonical species identity -------------------
    # Both RESTRICT — see the module docstring. A masking guard table must
    # never be emptied as a side effect of a taxa delete / re-seed.
    op.create_foreign_key(
        SENSITIVITY_FK,
        SENSITIVITIES_TABLE,
        "taxa",
        ["taxon_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        OVERRIDE_FK,
        OVERRIDES_TABLE,
        "taxa",
        ["taxon_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # --- 5. Recreate the indexes / uniques under their original names --------
    op.create_unique_constraint(
        "ux_taxon_sensitivities_taxon_source",
        SENSITIVITIES_TABLE,
        ["taxon_id", "source"],
    )
    op.create_index(
        "ix_taxon_sensitivities_taxon", SENSITIVITIES_TABLE, ["taxon_id"]
    )
    op.create_index(
        "ux_taxon_overrides_applied_unique",
        OVERRIDES_TABLE,
        ["project_id", "taxon_id"],
        unique=True,
        postgresql_where=sa.text("approval_status = 'applied'"),
    )
    op.create_index(
        "ix_taxon_overrides_taxon_approval",
        OVERRIDES_TABLE,
        ["taxon_id", "approval_status"],
    )


def downgrade() -> None:
    """Revert both columns to the legacy ``VARCHAR(64)`` string key.

    The re-keyed UUID values have no meaning in the old (three-way split)
    string key-space, so the downgrade truncates as well. Re-seeding is the
    documented recovery path in both directions.
    """
    op.drop_index("ix_taxon_overrides_taxon_approval", table_name=OVERRIDES_TABLE)
    op.drop_index("ux_taxon_overrides_applied_unique", table_name=OVERRIDES_TABLE)
    op.drop_index("ix_taxon_sensitivities_taxon", table_name=SENSITIVITIES_TABLE)
    op.drop_constraint(
        "ux_taxon_sensitivities_taxon_source",
        SENSITIVITIES_TABLE,
        type_="unique",
    )

    op.drop_constraint(OVERRIDE_FK, OVERRIDES_TABLE, type_="foreignkey")
    op.drop_constraint(SENSITIVITY_FK, SENSITIVITIES_TABLE, type_="foreignkey")

    op.execute(sa.text(f"TRUNCATE TABLE {OVERRIDES_TABLE}"))
    op.execute(sa.text(f"TRUNCATE TABLE {SENSITIVITIES_TABLE}"))

    op.drop_column(OVERRIDES_TABLE, "taxon_id")
    op.add_column(
        OVERRIDES_TABLE,
        sa.Column("taxon_id", sa.String(length=64), nullable=False),
    )
    op.drop_column(SENSITIVITIES_TABLE, "taxon_id")
    op.add_column(
        SENSITIVITIES_TABLE,
        sa.Column("taxon_id", sa.String(length=64), nullable=False),
    )

    op.create_unique_constraint(
        "ux_taxon_sensitivities_taxon_source",
        SENSITIVITIES_TABLE,
        ["taxon_id", "source"],
    )
    op.create_index(
        "ix_taxon_sensitivities_taxon", SENSITIVITIES_TABLE, ["taxon_id"]
    )
    op.create_index(
        "ux_taxon_overrides_applied_unique",
        OVERRIDES_TABLE,
        ["project_id", "taxon_id"],
        unique=True,
        postgresql_where=sa.text("approval_status = 'applied'"),
    )
    op.create_index(
        "ix_taxon_overrides_taxon_approval",
        OVERRIDES_TABLE,
        ["taxon_id", "approval_status"],
    )
