"""Clip Embedding model.

This model stores embedding vectors for audio clips generated by
ML models like BirdNET (1024 dimensions) or Perch 2.0 (1536 dimensions).
These embeddings enable similarity search and clustering of audio clips
using pgvector's vector similarity functions.
"""

from typing import TYPE_CHECKING
from uuid import UUID, uuid4

import sqlalchemy.orm as orm
from pgvector.sqlalchemy import Vector
from sqlalchemy import ForeignKey, UniqueConstraint

from echoroo.models.base import Base
from echoroo.models.clip import Clip

if TYPE_CHECKING:
    from echoroo.models.model_run import ModelRun

__all__ = [
    "ClipEmbedding",
]


class ClipEmbedding(Base):
    """Clip Embedding model.

    Stores embedding vectors for audio clips. Each embedding is associated
    with a specific clip and the model run that generated it.

    Notes
    -----
    The embedding dimension is set to 1536 to accommodate Perch 2.0 embeddings.
    BirdNET embeddings (1024 dimensions) will be zero-padded to fit.
    """

    __tablename__ = "clip_embedding"
    __table_args__ = (
        UniqueConstraint(
            "clip_id",
            "model_run_id",
        ),
    )

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True, init=False)
    """The database id of the clip embedding."""

    uuid: orm.Mapped[UUID] = orm.mapped_column(
        default_factory=uuid4,
        kw_only=True,
        unique=True,
    )
    """The UUID of the clip embedding."""

    clip_id: orm.Mapped[int] = orm.mapped_column(
        ForeignKey("clip.id", ondelete="CASCADE"),
        nullable=False,
    )
    """The database id of the clip to which this embedding belongs."""

    model_run_id: orm.Mapped[int] = orm.mapped_column(
        ForeignKey("model_run.id", ondelete="CASCADE"),
        nullable=False,
    )
    """The database id of the model run that generated this embedding."""

    embedding: orm.Mapped[list[float]] = orm.mapped_column(
        Vector(1536),
        nullable=False,
    )
    """The embedding vector (1536 dimensions for Perch 2.0 compatibility)."""

    # Relations
    clip: orm.Mapped[Clip] = orm.relationship(
        init=False,
        repr=False,
        lazy="joined",
    )
    """The clip to which this embedding belongs."""

    model_run: orm.Mapped["ModelRun"] = orm.relationship(
        init=False,
        repr=False,
        lazy="joined",
    )
    """The model run that generated this embedding."""
