"""Sound Event Embedding model.

This model stores embedding vectors for sound events generated by
ML models like BirdNET (1024 dimensions) or Perch 2.0 (1536 dimensions).
These embeddings enable similarity search and clustering of sound events
using pgvector's vector similarity functions.
"""

from typing import TYPE_CHECKING
from uuid import UUID, uuid4

import sqlalchemy.orm as orm
from pgvector.sqlalchemy import Vector
from sqlalchemy import ForeignKey, UniqueConstraint

from echoroo.models.base import Base
from echoroo.models.sound_event import SoundEvent

if TYPE_CHECKING:
    from echoroo.models.model_run import ModelRun

__all__ = [
    "SoundEventEmbedding",
]


class SoundEventEmbedding(Base):
    """Sound Event Embedding model.

    Stores embedding vectors for sound events. Each embedding is associated
    with a specific sound event and the model run that generated it.

    Notes
    -----
    The embedding dimension is set to 1536 to accommodate Perch 2.0 embeddings.
    BirdNET embeddings (1024 dimensions) will be zero-padded to fit.
    """

    __tablename__ = "sound_event_embedding"
    __table_args__ = (
        UniqueConstraint(
            "sound_event_id",
            "model_run_id",
        ),
    )

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True, init=False)
    """The database id of the sound event embedding."""

    uuid: orm.Mapped[UUID] = orm.mapped_column(
        default_factory=uuid4,
        kw_only=True,
        unique=True,
    )
    """The UUID of the sound event embedding."""

    sound_event_id: orm.Mapped[int] = orm.mapped_column(
        ForeignKey("sound_event.id", ondelete="CASCADE"),
        nullable=False,
    )
    """The database id of the sound event to which this embedding belongs."""

    model_run_id: orm.Mapped[int] = orm.mapped_column(
        ForeignKey("model_run.id", ondelete="CASCADE"),
        nullable=False,
    )
    """The database id of the model run that generated this embedding."""

    embedding: orm.Mapped[list[float]] = orm.mapped_column(
        Vector(),
        nullable=False,
    )
    """The embedding vector (dynamic dimensions - 1024 for BirdNET, 1536 for Perch)."""

    # Relations
    sound_event: orm.Mapped[SoundEvent] = orm.relationship(
        init=False,
        repr=False,
        lazy="joined",
    )
    """The sound event to which this embedding belongs."""

    model_run: orm.Mapped["ModelRun"] = orm.relationship(
        init=False,
        repr=False,
        lazy="joined",
    )
    """The model run that generated this embedding."""
