"""Bundled vernacular-name datasets.

Files in this package are generated by
``apps/api/scripts/build_vernacular_bundle.py`` and are loaded at runtime by
``echoroo.services.vernacular_bundle``:

* ``ioc_ja.csv`` — ``scientific_name,name`` Japanese names from the IOC World
  Bird List (Multilingual). Licensed CC BY 3.0 Unported.
* ``birdnet_crosswalk.csv`` — maps BirdNET V2.4 label scientific names (which
  follow eBird/Clements) onto AviList scientific names (which the IOC list
  tracks), so genus revisions do not silently drop a Japanese name.
  Licensed CC BY 4.0.
* ``birdnet_unresolved.txt`` — BirdNET labels that no crosswalk rule matched,
  kept for manual curation.
* ``overrides.csv`` — hand-maintained BirdNET → AviList scientific-name pairs
  consumed by the build script.

See ``THIRD_PARTY_LICENSES.md`` for the full attribution text.
"""
