"""Add unique index on ``search_sessions.celery_job_id``.

Revision ID: 0023
Revises: 0022
Create Date: 2026-04-23 00:00:00.000000

The ``celery_job_id`` column on ``search_sessions`` is populated with a
UUID4 generated by the API when a batch Celery task is dispatched. Three
lookups in the codebase (``workers/search_tasks.py``,
``api/v1/search/batch.py`` and ``services/search_session.py``) rely on
``.scalar_one_or_none()`` and therefore expect uniqueness at the DB layer.
Collision risk is negligible with UUID4, but enforcing the invariant in
the schema protects against any future code path that might introduce
duplicates.

PostgreSQL unique indexes treat NULL values as distinct, so a partial
index is not required to keep the column nullable.
"""

from __future__ import annotations

from alembic import op

# Revision identifiers used by Alembic.
revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create the unique index on ``search_sessions.celery_job_id``."""
    op.create_index(
        "ix_search_sessions_celery_job_id",
        "search_sessions",
        ["celery_job_id"],
        unique=True,
    )


def downgrade() -> None:
    """Drop the unique index on ``search_sessions.celery_job_id``."""
    op.drop_index(
        "ix_search_sessions_celery_job_id",
        table_name="search_sessions",
    )
